### ISSUE TITLE
Video quality issue at receivers end

### ISSUE THREAD

**Issue by soham24** [videosdk-live/videosdk-rtc-android-java-sdk-example#22]
I have streaming video in HD quality with this config.

CustomStreamTrack videoCustomTrack = VideoSDK.createCameraVideoTrack("h720p_w1280p", "front", this)

the quality of local connection is very good(camera view at local phone). but is getting degraded on the other end despite of using "h720p_w1280p" config.

what is the possible way to preserve the quality over the streaming?

**Comment by rajansurani** [comment]
Are you using setQuality() or setViewport() in to set the quality of the participant?

**Comment by soham24** [comment]
Right now is shown in example;
 participant.setViewPort(holder.itemView.getWidth(), holder.itemView.getHeight());
what is ideal? @rajansurani

**Comment by rajansurani** [comment]
Its Ideal to use setViewport() to optimize the performance when there are large number of participants as it will adjust the quality of video based on the size of view. 

If you want to use video call for 2-3 participants its completely fine to not use this method. You can use the setQuality() methods in that case.

**Comment by soham24** [comment]
Thank you.  We will only have 2 participants at a time.

**Comment by rajansurani** [comment]
Then you can avoid using the setViewport() and you will get the best possible quality.

**Comment by soham24** [comment]
thank you @rajansurani
