### ISSUE TITLE
Need to flip front camera 

### ISSUE THREAD

**Issue by soham24** [videosdk-live/videosdk-rtc-android-java-sdk-example#24]
We want the front camera to be mirrored. Do you have the functionality for it?

**Comment by rajansurani** [comment]
@soham24  You can use `svrLocal.setMirror(true);` to get the mirror effect.

`svrLocal` here is the SurfaceViewRenderer of the participant

**Comment by soham24** [comment]
@rajansurani Thanks you, it works.
I want to do a mirror only on the front camera.
i.e. when it's back camera, it should be setMirror(false).
Is there any way to get cameraId in the ParticipantAdapter to set the above conditions.

**Comment by rajansurani** [comment]
@soham24 You can maintain a local flag `isFront` and basis that you can update the `setMirror(isFront)`.

Set the initial state of the `isFront`  as `true` if you turning on front camera by default.

Currently we don't have a property through which you can now the `cameraId`.

**Comment by soham24** [comment]
@rajansurani thank you. Can we expect this functionality in near future? 
Calling meeting.changeWebcam()  returns : frontcam, front cam zoomed , backcam. 
is it intended functionality?

**Comment by rajansurani** [comment]
@soham24 Sure. Will take it in our backlog.
