### ISSUE TITLE
Jitpack library not accessible 

### ISSUE THREAD

**Issue by HritikBhat** [videosdk-live/videosdk-rtc-android-java-sdk-example#38]
I ran the code and got this error "Could not GET 'https://jitpack.io/live/videosdk/videosdk-room-stats-android/0.0.1/videosdk-room-stats-android-0.0.1.pom'. Received status code 401 from server: Unauthorized" while Grade Build Running.

Please kindly solve this issue.

Thank You

**Comment by ishabodiwala** [comment]
Hey @HritikBhat, please update the `main` branch and try again.

**Comment by ishabodiwala** [comment]
Hey @HritikBhat, please update the `main` branch and try again.
